server {
    listen 80;
    server_name pgadmin.multipath.net.pe;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name pgadmin.multipath.net.pe;

    ssl_certificate /etc/nginx/ssl/pgadmin.multipath.net.pe.crt;
    ssl_certificate_key /etc/nginx/ssl/pgadmin.multipath.net.pe.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    #set $upstream c_pgadmin;
    location / {
        proxy_pass http://c_pgadmin:5050;
        # proxy_pass http://$upstream:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # Cabeceras críticas para sesiones
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;

        # Timeouts
        proxy_connect_timeout 360s;
        proxy_send_timeout 360s;
        proxy_read_timeout 360s;

        # WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Buffers
        proxy_buffering off;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }
}
