server {
    listen 80;
    server_name pgadmin.multipath.net.pe;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name pgadmin.multipath.net.pe;
    ssl_certificate     /etc/nginx/ssl/pgadmin.multipath.net.pe.crt;
    ssl_certificate_key /etc/nginx/ssl/pgadmin.multipath.net.pe.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    resolver 127.0.0.11 valid=30s;
    set $upstream c_pgadmin;
    location / {
        proxy_pass http://$upstream:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
