services:
  postgres:
    image: postgres:16
    container_name: c_postgres_saas
    restart: unless-stopped
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_pass
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - internal_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: c_pgadmin_saas
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@midominio.com
      PGADMIN_DEFAULT_PASSWORD: CAMBIAR_PASSWORD
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal_net
    # ⚠️ NO exponer puertos a internet en SaaS real
    ports:
      - "127.0.0.1:5050:5050"

  nginx:
    image: nginx:1.26.1
    container_name: c_nginx_saas
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../nginx/certs:/etc/nginx/ssl
      - ../nginx/logs:/var/log/nginx
    networks:
      - internal_net
      - public_net

networks:
  internal_net:
    name: internal_net
    driver: bridge
    internal: true

  public_net:
    name: public_net
    driver: bridge
