services:
  odoo:
    image: odoo:18
    user: "100:101"
    container_name: c_odoo_CLIENT_NAME
    restart: unless-stopped
    environment:
      - TZ=America/Lima
      - LANG=es_PE.UTF-8
      - HOST=postgres
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - DB_NAME=CLIENT_NAME
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./addons:/mnt/extra-addons
      - ./data:/var/lib/odoo
      - ./logs:/var/log/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    networks:
      - internal_net

networks:
  internal_net:
    external: true
